### PR TITLE
Fix the member multiple injection

### PR DESCRIPTION
**Pull request by ooonush**
Fixed multiple injection in the inheritance. Issue: #496 and also #486.

There remains one more unpleasant bug that I could not fix elegantly: https://github.com/hadashiA/VContainer/issues/501

### CODE REVIEW

**Comment by hadashiA** [comment]
Thanks a lot.

Let me check a few things.

Also, I think the SourceGenerator side needs to be fixed as well,
I may possibly re-create the PR on my end with this as a reference. Please understand.

**Comment by hadashiA** [comment]
@ooonush Hi. I have created #505 with considerable help from this PR.
I think I was able to fix the problems in #496 , #486 and #501.
Thanks a lot. I would appreciate it if you could let me know if there are any problems.

**Comment by ooonush** [comment]
Great, thanks. And what do you think about using HashSet to check for duplicate MemberInfo's? You could create an IEqualityComparer that compares by member.GetBaseDefinition(). That should work faster than a full search.

**Comment by hadashiA** [comment]
> do you think about using HashSet to check for duplicate MemberInfo's?

Depends on the number of Inject methods.
In most cases, there will likely be at most one Inject method, so we consider the method with the least overhead to be the best.

**Pull request closed without merging**
