### PR TITLE
Proofread constructor-injection.mdx

### PR DESCRIPTION
**Pull request by JesseTG**

### CODE REVIEW

**Comment by hadashiA** [comment]
The content is probably fine 👍 

Seems to be found broken links.


> 04:10:53.001 | Error: Docusaurus found broken links!

> 04:10:53.001 | Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
> 04:10:53.001 | Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
> 04:10:53.001 | Exhaustive list of all broken links found:
> 04:10:53.002 | - On source page path = /resolving/constructor-injection:
> 04:10:53.002 | -> linking to some (resolved as: /resolving/some)
> 04:10:53.002 | -> linking to exceptions (resolved as: /resolving/exceptions)
> 04:10:53.002 | -> linking to methods (resolved as: /resolving/methods)

**Comment by JesseTG** [comment]
I'll take a closer look.

**Comment by JesseTG** [comment]
Whoops! I mixed up the link syntax in a few places. My bad.

**Comment by hadashiA** [comment]
Thanks for fixing 👍

**Pull request merged**
